"""FleetTwin shared contract. READ-ONLY for agents (owner: Hemanth).

Every lane imports these types. If something is missing or wrong, log it in
HANDOFF.md; do not edit this file.
Units: meters, seconds, radians, battery %, temperature degC, current A,
vibration g RMS. Time `ts` is simulation time in seconds.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field

RobotType = Literal["rover", "drone", "agv"]
TwinMode = Literal["synced", "dead_reckoning"]
Severity = Literal["info", "warn", "critical"]
HealthStatus = Literal["ok", "watch", "maintenance", "critical"]
Action = Literal[
    "CONTINUE", "REROUTE", "RETURN_TO_BASE", "QUARANTINE_TELEMETRY", "SCHEDULE_MAINTENANCE"
]
AttackKind = Literal[
    "noise", "dropout", "spoof_freeze", "spoof_jump", "spoof_drift", "spoof_battery"
]
EventKind = Literal[
    "deviation", "deviation_cleared",
    "spoof_suspected",
    "noise_high", "noise_cleared",
    "dropout", "link_recovered",
    "health_warning", "maintenance_due",
    "mission_deployed", "override",
    "attack_injected", "attack_cleared",
]


class StateVec(BaseModel):
    x: float
    y: float
    z: float = 0.0
    heading: float
    speed: float
    battery: float
    motor_temp: float
    current: float
    vibration: float


class Telemetry(StateVec):
    """One packet from a robot (flat JSON)."""
    robot_id: str
    robot_type: RobotType
    ts: float
    seq: int
    sig: Optional[str] = None  # HMAC-SHA256 hex; None when signing is off


class Waypoint(BaseModel):
    x: float
    y: float
    z: float = 0.0


class Mission(BaseModel):
    mission_id: str
    robot_id: str
    waypoints: list[Waypoint]
    cruise_speed: float
    loop: bool = False


class TwinState(BaseModel):
    """Twin output for one robot after each packet (or tick)."""
    robot_id: str
    ts: float
    mode: TwinMode
    pred: StateVec                  # one-step-ahead prediction made BEFORE seeing the packet
    est: StateVec                   # corrected estimate
    residual_pos: float             # |observed_xy - pred_xy| in meters
    residual_norm: float            # normalized multi-channel residual (dimensionless)
    cross_track_err: float          # meters from planned path (0 if no mission)
    heading_err: float              # radians vs planned segment heading
    plan_x: Optional[float] = None  # where the plan says the robot should be now
    plan_y: Optional[float] = None
    sync_score: float               # 0-100
    confidence: float               # 0-1 (decays in dead_reckoning)
    since_last_packet_s: float = 0.0


class TwinSnapshot(BaseModel):
    """Forkable twin state used by the mission sandbox."""
    robot_id: str
    robot_type: RobotType
    ts: float
    est: StateVec
    mission: Optional[Mission] = None
    waypoint_idx: int = 0


class HealthReport(BaseModel):
    robot_id: str
    ts: float
    health_index: float              # 1.0 healthy -> 0.0 failed
    rul_s: Optional[float] = None    # remaining useful life (seconds), None if unknown
    rul_low_s: Optional[float] = None
    rul_high_s: Optional[float] = None
    status: HealthStatus = "ok"
    drivers: dict[str, float] = Field(default_factory=dict)  # e.g. {"current": .., "temp": .., "vib": ..}


class Event(BaseModel):
    id: str
    ts: float
    robot_id: Optional[str] = None
    kind: EventKind
    severity: Severity
    message: str
    detail: dict = Field(default_factory=dict)


class Decision(BaseModel):
    action: Action
    reason: str
    confidence: float                # 0-1
    robot_id: Optional[str] = None   # None = fleet-level
    override_active: bool = False


class OverrideState(BaseModel):
    robot_id: Optional[str] = None
    action: Action
    seconds_left: float


class AttackSpec(BaseModel):
    """magnitude: noise=sigma (m), spoof_jump=offset (m), spoof_drift=speed (m/s),
    spoof_battery=battery offset (%). Ignored for dropout and spoof_freeze."""
    robot_id: str
    kind: AttackKind
    magnitude: float = 1.0
    duration_s: float = 10.0


class GroundTruth(BaseModel):
    robot_id: str
    wear: float                                  # 0-1, failure at 1.0
    time_to_failure_s: Optional[float] = None
    attack_active: Optional[AttackKind] = None


class SimResult(BaseModel):
    mission_id: str
    robot_id: str
    eta_s: float
    end_battery: float
    risk: float                                  # 0-1
    path: list[tuple[float, float]]              # downsampled to <= 200 points
    violations: list[str] = Field(default_factory=list)
    safe_to_deploy: bool
    notes: str = ""


class RobotFrame(BaseModel):
    robot_id: str
    robot_type: RobotType
    name: str
    telemetry: Telemetry
    twin: TwinState
    health: HealthReport
    decision: Decision
    mission: Optional[Mission] = None
    active_attacks: list[AttackKind] = Field(default_factory=list)


class IngestStats(BaseModel):
    msgs_per_s: float = 0.0
    dropped: int = 0
    lag_ms: float = 0.0


class StreamFrame(BaseModel):
    """Pushed over SSE at 5 Hz."""
    ts: float
    robots: list[RobotFrame]
    events: list[Event] = Field(default_factory=list)  # new since last frame
    fleet_sync: float
    ingest: IngestStats = Field(default_factory=IngestStats)


class EvalRow(BaseModel):
    scenario: str
    kind: str
    magnitude: float
    detected: bool
    time_to_detect_s: Optional[float] = None
    false_alarms: int = 0
    min_sync: float = 100.0
    recovery_s: Optional[float] = None


class EvalSummary(BaseModel):
    detection_rate: float
    false_alarms_per_hour: float
    mean_time_to_detect_s: Optional[float] = None
    mean_recovery_s: Optional[float] = None
    rul_error_pct: Optional[float] = None
    mean_sync_clean: float
    mean_sync_attacked: float


class EvalResult(BaseModel):
    seed: int
    ts: float
    rows: list[EvalRow]
    summary: EvalSummary


class Token(BaseModel):
    access_token: str
    role: Literal["operator", "viewer"]
